Repository KamilSupera/quickTrav, pull requests merged in 2019-03, with the labels that each got.

#29 Feature/stops to drawer
  app/src/main/java/com/example/supera/kamil/quicktravel/activities/MainActivity.java
  app/src/main/res/menu/drawer_menu.xml
Labels: enhancement

#35 Get position device and and add mark in on map
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/supera/kamil/quicktravel/fragments/GoogleMapFragment.java
  app/src/main/java/com/example/supera/kamil/quicktravel/fragments/GoogleSignInFragment.java
  app/src/main/java/com/example/supera/kamil/quicktravel/gps_location/CityLookupFail.java
  app/src/main/java/com/example/supera/kamil/quicktravel/gps_location/DeviceDisabled.java
  app/src/main/java/com/example/supera/kamil/quicktravel/gps_location/GPSLocation.java
Labels: enhancement

#39 Refactor firebase loading
  app/src/main/java/com/example/supera/kamil/quicktravel/activities/MainActivity.java
  app/src/main/java/com/example/supera/kamil/quicktravel/activities/SplashScreen.java
  app/src/main/java/com/example/supera/kamil/quicktravel/firebase/mapper/FirebaseMapper.java
  app/src/main/java/com/example/supera/kamil/quicktravel/fragments/GoogleMapFragment.java
  app/src/main/java/com/example/supera/kamil/quicktravel/mapper/FirmMapper.java
  app/src/main/java/com/example/supera/kamil/quicktravel/mapper/OwnerCommentMapper.java
  app/src/main/java/com/example/supera/kamil/quicktravel/mapper/RouteMapper.java
  app/src/main/java/com/example/supera/kamil/quicktravel/mapper/StopMapper.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/Departure.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/Firm.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/OwnerComment.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/Route.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/Stop.java
  app/src/main/java/com/example/supera/kamil/quicktravel/repository/RouteRepository.java
  app/src/main/java/com/example/supera/kamil/quicktravel/repository/StopRepository.java
  app/src/main/java/com/example/supera/kamil/quicktravel/viewmodels/AppViewModel.java
  app/src/main/java/com/example/supera/kamil/quicktravel/viewmodels/StopViewModel.java
Labels: refactor

#41 Add full mapper for OwnerComment model
  app/src/main/java/com/example/supera/kamil/quicktravel/mapper/OwnerCommentMapper.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/OwnerComment.java
Labels: enhancement, refactor

#43 Fix Departures model and mapper
  app/src/main/java/com/example/supera/kamil/quicktravel/mapper/StopMapper.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/Departure.java
Labels: bug

#47 Add timetable
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/supera/kamil/quicktravel/NoStop.java
  app/src/main/java/com/example/supera/kamil/quicktravel/activities/RouteDetailActivity.java
  app/src/main/java/com/example/supera/kamil/quicktravel/activities/StopsActivity.java
  app/src/main/java/com/example/supera/kamil/quicktravel/fragments/DeparturesWorker.java
  app/src/main/java/com/example/supera/kamil/quicktravel/mapper/StopMapper.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/Departure.java
  app/src/main/java/com/example/supera/kamil/quicktravel/models/Route.java
  app/src/main/res/layout/departures.xml
  app/src/main/res/layout/departures_worker.xml
  app/src/main/res/values/strings.xml
Labels: enhancement
